name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build -t devops-beginner:latest .

      - name: Docker Tag
        run: |
          echo ${{ secrets.DOCKER_USERNAME }}
          docker tag devops-beginner:latest ${{ secrets.DOCKER_USERNAME }}/devops-beginner:latest

      - name: Docker Login # login to Docker Hub using Personal Access Token
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Docker Push
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}"/devops-beginner:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy files
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./* ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/devops-beginner

      - name: Deploy to K3s
        run: |
          ssh -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            ${{ secrets.USER }}@${{ secrets.HOST }} \
            "sudo kubectl apply -f /home/user/k3s-manifest.yaml"
